### ISSUE TITLE
Gaps in railway lines in low zoom levels

### ISSUE THREAD

**Issue by DerDakon** [rurseekatze/node-tileserver#74]
![21](https://cloud.githubusercontent.com/assets/10909049/11164498/c97b2720-8af2-11e5-96a7-bc9d6d79a0aa.png)

The above example is http://a.tiles.openrailwaymap.org/standard/6/33/21.png as of today. Basically all of these gaps are filled with main or highspeed lines in zoom level 7.

**Comment by rurseekatze** [comment]
I guess this is the reason: https://github.com/rurseekatze/node-tileserver/blob/4ef20d2b215c7eed17dc45f7dd460d6e56aa0bfd/tile.js#L580

I do not know why this LIMIT is contained in the query. I guess that it was already contained in the json_getter.py from KothicJS.

Simply removing the limit should fix the problem. But this issue shows that there is a huge problem with too big vector tiles on low zoom levels. There should not be more than 10.000 features necessary for rendering just this single tile. The problem occurs because there are lots of very short ways that are not merged in lower zoom levels.

I propose to fix this issue by removing the LIMIT statement and opening a separate issue for collecting ideas of reducing the number of features in low zoom levels.

**Comment by rurseekatze** [comment]
Ideas for reducing the number of ways can be collected in #116.
